sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pratikshitsingh/single-container-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pratikshitsingh/single-container-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-211125434210"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
